### ISSUE TITLE
[Suggestion] Put older versions on Modrinth

### ISSUE THREAD

**Issue by GoldenFurredFox** [Ladysnake/BLAST#52]
### Mod Loader

Fabric

### Minecraft Versions

1.14.4, 1.15.1, 1.16-Snapshot, 1.16.1, 1.16.3, 1.16.4, 1.16.5, 1.17, 1.17-Snapshot, 1.17.1, 1.18, 1.18.1, 1.18.2, 1.19, 1.19.1 

### Mod Versions

1.0.0, 1.1.0, 1.1.1, 1.2, 1.2.1, 1.3, 1.3.1, 1.3.2, 1.4, 1.5, 1.5.1, 1.5.2, 1.6, 1.6.1, 1.6.2, 1.7, 1.7.1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.9, 1.9.1, 1.10

### Suggestion

It'd improve my quality of life, and I'm sure the quality of life of many others, if you'd add the mod versions prior to Minecraft version 1.19.2 to your Modrinth release page for BLAST.

**Comment by Xiribidus** [comment]
Except for 1.3.1 (server crash), 1.7 (bomb throwing issues) and 1.9 (severe render distance issue) they should be all up now, although they are currently only stated to support fabric and their specific release version, nothing else since I do not want to enter false statements there or test through what minor versions do or do not work.
